name: Build and Deploy to oracle cloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: oraclecloud
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  build-image:
    needs: [build]
    runs-on: oraclecloud
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN}}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64, linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ktx-gacha:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
    # - name: Run Tests
    #   env: 
    #     SECRET_KEY: ${{ secrets.SECRET_KEY }}
    #   run: |
    #     python manage.py test
